ROLE_PERMISSIONS = {
    "thesis_narrative": {
        "researcher": "write",
        "critic": "no",
        "quant": "no",
        "trader": "no",
        "aaron": "override",
        "system": "no",
    },
    "falsifiers": {
        "researcher": "write",
        "critic": "trigger/escalate",
        "quant": "no",
        "trader": "limited",
        "aaron": "override",
        "system": "no",
    },
    "scoring_regime_analytics": {
        "researcher": "no",
        "critic": "no",
        "quant": "write",
        "trader": "read",
        "aaron": "override",
        "system": "derived",
    },
    "execution_plan": {
        "researcher": "read",
        "critic": "review",
        "quant": "assist",
        "trader": "write",
        "aaron": "override",
        "system": "no",
    },
    "position_quantities": {
        "researcher": "no",
        "critic": "no",
        "quant": "derived",
        "trader": "write",
        "aaron": "override",
        "system": "derived",
    },
    "risk_policy": {
        "researcher": "read",
        "critic": "read",
        "quant": "read",
        "trader": "read",
        "aaron": "write",
        "system": "enforce",
    },
    "audit_log": {
        "researcher": "append_own",
        "critic": "append_own",
        "quant": "append_own",
        "trader": "append_own",
        "aaron": "append",
        "system": "append_derived",
    },
}
